# Generated by Django 5.1.3 on 2024-11-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_remove_receipe_deleted_receipe_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedRecipe',
        ),
    ]
